### ISSUE TITLE
Real cursor still visible on Firefox Linux

### ISSUE THREAD

**Issue by edge0701** [javierbyte/click-of-death#4]
As title; cursor is still visible on Firefox (52.0.2 (64-bit) on Arch Linux).
But works as expected on Chromium on same OS.
Also works correctly on FF and Chrome on Debian.
Clever stuff, I like it 👍

**Comment by javierbyte** [comment]
@edge0701 can you please let me know if this is still happening to you?

**Comment by sovietspaceship2** [comment]
I can confirm, real cursor hidden in chromium but visible in firefox

**Comment by javierbyte** [comment]
@sovietspaceship @edge0701 I can not reproduce it myself :( can any of you please confirm if any of the 

```css
* {
  cursor: url(./assets/16.png), default;
  cursor: none;
}
```

are active?

**Comment by sovietspaceship2** [comment]
I get `Invalid property value` for `cursor: url(./assets/16.png), default;`

**Comment by javierbyte** [comment]
@sovietspaceship thank you! can you please try again? I removed that property and now I'm only using `cursor: none`.

**Comment by sovietspaceship** [comment]
No luck. Trying to understand why this happens, but looks like Firefox until 54 does not fully support this

**Comment by sovietspaceship2** [comment]
It works now.

**Comment by javierbyte** [comment]
Thank you @sovietspaceship !

**Comment by edge0701** [comment]
I didn't have a problem with the replaced cursor image - that was always visible. But my actual cursor is still visible on full refresh on Firefox ArchLinux at http://javier.xyz/control-user-cursor/. Same issue when running your source code, too. Funnily enough, the real cursor does actually disappear when I mouse over the top left title & buttons, but is visible in the main content area.

Okay, so I did a bit more digging. I can get the cursor to dissapear if css for #container has height: 100%. But then the replacement cursor also disappears. The only way that it works I have found so far, is if the replacement cursor `<img/>` element is placed as a child inside the container div.

I've tried doing this programatically for you, but you need to run the setup code inside a `document.addEventListener("DOMContentLoaded", function() {});` otherwise I can't appendChild to the #container.

Hope this helps.
